[SHLD-MTN-27836] Migrate Legacy webservices code examples to public repository
Twinfield/twinfield-api-reference pull request #1
Opened 2023-02-27 06:20 UTC by Ketan-D

2023-03-01 12:40 UTC, mdenekamp commented on ExampleCsharp/Twinfield Webservices Sample C-sharp/Program.cs
> +			var organization = Console.ReadLine().ToUpper();
There is currently some inconsistency between naming. For instance, in the switch statement, there's an OrganisationInactive case. For the sake of consistency, I think it would be good to rename variables and comments to _organisation_.

2023-03-01 12:46 UTC, mdenekamp commented on ExampleCsharp/Twinfield Webservices Sample C-sharp/Program.cs
> +			// Create the session.
Do we really need comments in classes, or should better names be picked?

2023-03-01 12:52 UTC, mdenekamp commented on ExampleCsharp/Twinfield Webservices Sample C-sharp/Program.cs
> +					if (timeout > 0)
To reduce nesting, the logic could be reversed which should get rid of the else statement.

2023-03-01 12:54 UTC, mdenekamp commented on ExampleCsharp/Twinfield Webservices Sample C-sharp/Program.cs
> +					ExitProgram("Log-on is blocked.");
A dash between Log and On is not needed. It's either a logon (noun) or a log on (verb).

2023-03-01 13:18 UTC, mdenekamp commented on ExampleCsharp/Twinfield Webservices Sample C-sharp/Program.cs
> +				else if (nextAction == LogonAction.ChangePassword)
In the previous function, a switch statement was used and here is a lot of nesting in if, else-if and else statements. Perhaps it would be good to create some consistency in the way the conditions are written.

2023-03-01 13:19 UTC, mdenekamp commented on ExampleCsharp/Twinfield Webservices Sample C-sharp/Program.cs
> +		static void ExitProgram(string message = null)
Default value for string is already null.

2023-03-01 13:20 UTC, mdenekamp commented on ExampleCsharp/Twinfield Webservices Sample C-sharp/Program.cs
> +				Console.WriteLine("ProcessXml: Displaying a list of offices... ");
As the function is called DisplayCompanies, it would be good to also state that in the feedback we provide in the console.

2023-03-01 14:09 UTC, SuperRembo requested changes
This is just a brushed up version of the old example. It still doesn't use OAuth to authenticate, so it doesn't work on production. 

Like I said before, I would go all the way back to the start. Throw everything away. Write down what an example program should be able to do. What is the purpose? Then build that with modern tools. 

And don't worry about throwing away this code, I think I wrote most of it, and I don't sleep any minute less when it's deleted (maybe I'd sleep better when it's deleted 💤)

2023-03-01 14:58 UTC, mdenekamp commented on ExampleCsharpExtended/TwinfieldApi/Bookkeeping/BookkeepingService.cs
> +			//TODO: Implement browse transactions
Should this TODO be resolved?

2023-03-01 14:59 UTC, mdenekamp commented on ExampleCsharp/Twinfield Webservices Sample C-sharp/Program.cs
> +			if (soapException == null) return;
Is this check relevant? The only way to get here is by catching the soap exception, so is there a way it could be null?

2023-03-01 15:03 UTC, mdenekamp commented on ExampleCsharp/Twinfield Webservices Sample C-sharp/Program.cs
> +			if (webException == null) return;
Similar to above, is there a way where the web exception can be null?

2023-03-01 15:08 UTC, mdenekamp commented on ExampleCsharpExtended/Demo/ApiDemo.cs
> +		bool SwitchToOffice(string office)
SwitchToCompany, company

2023-03-01 15:09 UTC, mdenekamp commented on ExampleCsharpExtended/Demo/BankBookDemo.cs
> +	class BankBookDemo
It's a Bankbook and not a BankBook.

2023-03-01 15:09 UTC, mdenekamp commented on ExampleCsharpExtended/Demo/BankBookDemo.cs
> +			Console.WriteLine("Read bank book");
Bankbook is a single word.

2023-03-01 15:11 UTC, mdenekamp commented on ExampleCsharp/Twinfield Webservices Sample C-sharp/Program.cs
> +	class Program
The length of the class seems a bit long. Recommended is around 200 lines and functions ideally are less than 20 lines each.

2023-03-01 15:12 UTC, mdenekamp commented on ExampleCsharpExtended/Demo/BookkeepingDemo.cs
> +			//TODO: Use browse results as input to read an existing transaction
Does this TODO need to be resolved?

2023-03-01 15:12 UTC, mdenekamp commented on ExampleCsharpExtended/Demo/BookkeepingDemo.cs
> +			//TODO: Get code and number of first transaction (to be used by read transaction)
Does this TODO need to be resolved?

2023-03-01 15:20 UTC, mdenekamp commented on ExampleCsharpExtended/README.md
> +==================
Perhaps we can provide some guidance in this README. For instance, the ambiguous use of organisation, organization and office and company.

2023-03-01 15:21 UTC, mdenekamp commented on ExampleCsharpExtended/TwinfieldApi/BankBooks/BankBook.cs
> +	public class BankBook
It's a Bankbook and not a BankBook.

2023-03-01 15:28 UTC, mdenekamp commented on ExampleCsharpExtended/TwinfieldApi/Service References/TwinfieldFinderService/Reference.svcmap
> +    <MetadataSource Address="https://c1.twinfield.com/webservices/finder.asmx" Protocol="http" SourceId="1" />
Seems to be pointing to an endpoint that doesn't exist anymore.

2023-03-01 15:29 UTC, mdenekamp commented on ExampleCsharpExtended/TwinfieldApi/Service References/TwinfieldFinderService/finder.disco
> +  <contractRef ref="https://c1.twinfield.com/webservices/finder.asmx?wsdl" docRef="https://c1.twinfield.com/webservices/finder.asmx" xmlns="http://schemas.xmlsoap.org/disco/scl/" />
Seems to be pointing to an endpoint that doesn't exist anymore.

2023-03-02 07:03 UTC, Ketan-D commented on ExampleCsharp/Twinfield Webservices Sample C-sharp/Program.cs
> +			// Create the session.
Agree. We should focus on better naming instead of providing comments.

2023-04-04 10:21 UTC, Ketan-D commented
This PR is not required now. We migrated the code examples to different GitHub repository.

2023-04-04 10:21 UTC, closed without merging